---
language: ruby
rvm:
- 2.6.3
sudo: false
cache: bundler
env:
- TASK='jekyll:check'
- TASK='jekyll:check_external_links'
matrix:
  fast_finish: true
  allow_failures:
  - env: TASK='jekyll:check_external_links'
script: bundle exec rake $TASK
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
